INSERT INTO USERS (EMAIL,LOGIN, NAME, BIRTHDAY) VALUES ('ivan@mail.ru', 'ivan', 'ivan', {ts '2000-09-17'});
INSERT INTO USERS (EMAIL,LOGIN, NAME, BIRTHDAY) VALUES ('elena@mail.ru', 'elene', 'elena', {ts '1991-12-11'});
INSERT INTO USERS (EMAIL,LOGIN, NAME, BIRTHDAY) VALUES ('sergey@mail.ru', 'sergey', 'sergey', {ts '1978-02-22'});
INSERT INTO USERS (EMAIL,LOGIN, NAME, BIRTHDAY) VALUES ('hastya@mail.ru', 'nastya', 'nastya', {ts '2007-03-07'});

INSERT INTO FILMS (NAME,DESCRIPTION, RELEASE_DATE, DURATION) VALUES ('Spy Game', 'Action', {ts '2001-11-21'}, 127);
INSERT INTO FILMS (NAME,DESCRIPTION, RELEASE_DATE, DURATION) VALUES ('Avatar: The Way of Water', 'Fantasy', {ts '2022-12-06'}, 192);
INSERT INTO FILMS (NAME,DESCRIPTION, RELEASE_DATE, DURATION) VALUES ('The Menu', 'Triller', {ts '2022-09-10'}, 107);
INSERT INTO FILMS (NAME,DESCRIPTION, RELEASE_DATE, DURATION) VALUES ('The Usual Suspects', 'Crime', {ts '1995-01-25'}, 106);

--INSERT INTO FRIENDUSERS (USER_ID,FRIEND_ID, FRIENDSHIP_CONFIRM ) VALUES ();
--INSERT INTO FRIENDUSERS (USER_ID,FRIEND_ID, FRIENDSHIP_CONFIRM ) VALUES ();

--INSERT INTO LIKES (FILM_ID, USER_ID) VALUES ();
--INSERT INTO LIKES (FILM_ID, USER_ID) VALUES ();
--INSERT INTO LIKES (FILM_ID, USER_ID) VALUES ();

