CREATE TABLE IF NOT EXISTS USERS (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING NOT NULL,
	LOGIN CHARACTER VARYING NOT NULL,
	NAME CHARACTER VARYING,
	BIRTHDAY TIMESTAMP NOT NULL,
	PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS FILMS (
	FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING NOT NULL,
	DESCRIPTION CHARACTER VARYING(200) NOT NULL,
	RELEASE_DATE TIMESTAMP NOT NULL,
	DURATION INTEGER NOT NULL,
	PRIMARY KEY (FILM_ID)
);

CREATE TABLE IF NOT EXISTS USERFRIENDS (
    USER_ID BIGINT NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	FRIENDSHIP_CONFIRM BOOLEAN NOT NULL
);
ALTER TABLE USERFRIENDS ADD CONSTRAINT USERFRIENDS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID);
ALTER TABLE USERFRIENDS ADD CONSTRAINT USERFRIENDS_FK_1 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(USER_ID);


CREATE TABLE IF NOT EXISTS LIKES (
	FILM_ID BIGINT NOT NULL,
	USER_ID INTEGER NOT NULL
);
ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT LIKES_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID);
ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT LIKES_FK_1 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID);


CREATE TABLE IF NOT EXISTS GENRES (
    FILM_ID BIGINT NOT NULL,
    GENRE CHARACTER VARYING NOT NULL
);
ALTER TABLE PUBLIC.GENRES ADD CONSTRAINT GENRES_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID);

