

CREATE TABLE USERS (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING NOT NULL,
	LOGIN CHARACTER VARYING NOT NULL,
	NAME CHARACTER VARYING,
	BIRTHDAY TIMESTAMP NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON USERS (USER_ID);


CREATE TABLE FILMS (
	FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING NOT NULL,
	DESCRIPTION CHARACTER VARYING(200) NOT NULL,
	RELEASE_DATE TIMESTAMP NOT NULL,
	DURATION INTEGER NOT NULL,
	CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_3 ON FILMS (FILM_ID);



CREATE TABLE FRIENDUSERS (
	USER_ID BIGINT NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	FRIENDSHIP_CONFIRM BOOLEAN NOT NULL,
	CONSTRAINT FRIENDUSERS_FK PRIMARY KEY (USER_ID,USER_ID),
	CONSTRAINT FRIENDUSERS_FK_1 PRIMARY KEY (USER_ID,USER_ID)
);
CREATE INDEX FRIENDUSERS_FK_INDEX_D ON FRIENDUSERS (USER_ID);

-- PUBLIC.FRIENDUSERS foreign keys

ALTER TABLE PUBLIC.FRIENDUSERS ADD CONSTRAINT FRIENDUSERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.FRIENDUSERS ADD CONSTRAINT FRIENDUSERS_FK_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;



CREATE TABLE LIKES (
	FILM_ID BIGINT NOT NULL,
	USER_ID INTEGER NOT NULL,
	CONSTRAINT LIKES_FK PRIMARY KEY (USER_ID,USER_ID),
	CONSTRAINT LIKES_FK_1 PRIMARY KEY (FILM_ID,FILM_ID)
);
CREATE INDEX LIKES_FK_1_INDEX_4 ON LIKES (FILM_ID);
CREATE INDEX LIKES_FK_INDEX_4 ON LIKES (USER_ID);


-- PUBLIC.LIKES foreign keys

ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT LIKES_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT LIKES_FK_1 FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;